### create a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name" : "Haribalan",
  "email" : "Kafka_Testing_apigate@gmail.com",
  "address" : "Madurai Indlaia",
  "dateOfBirth" : "2008-04-19",
  "registeredDate" : "2025-04-23"
}
###