### create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "Hema Sri",
  "email" : "hema@gmail.com",
  "address" : "Madurai India",
  "dateOfBirth" : "2008-04-19",
  "registeredDate" : "2025-04-10"
}
###